version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/progressSoft
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: superman
      SERVER_PORT: 8080
    depends_on:
      - db
    volumes:
      - maven-repo:/root/.m2

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superman
      POSTGRES_PORT: 5433
      POSTGRES_MULTIPLE_DATABASES: progressSoft, progressSoft_test
    ports:
      - "5433:5433"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    command: ["postgres", "-p", "5433"]

volumes:
  db_data:
  maven-repo: