spring:
  application:
    name: ProgressSoft Technical Assignment
  datasource:
    url: jdbc:postgresql://localhost:5433/progressSoft
    username: postgres
    password: superman
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080

logging:
  level:
    org.springframework.data.jpa.repository.query: debug
    org.progressSoft.fxDeals: trace